### ISSUE TITLE
`fs-storage`: Implement storages in Rust

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ark-core#1]
Right now, we have storages implemented in Kotlin. It would be great to move them from `arklib-android` repo to `arklib` and implement them in Rust. Then, we'll replace Kotlin code with JNI bindings to Rust code.

The original storages implementation is [here](https://github.com/ARK-Builders/arklib-android/tree/main/lib/src/main/java/dev/arkbuilders/arklib/data/storage). Any storage is just a KV-table. Usually, from with `ResourceId` as type for keys.

The original implementation contains also "**sync with disk**" functionality. We should carefully plan this feature. Probably, it should be separated from storages into _merge strategy_ for _atomic files_
* Skip the `Monoid` abstraction for this moment.
* Skip `AggregatedStorage` class for this moment.

- [x] `FileStorage` for keeping the table in a single file 
- [x] `FolderStorage` for keeping the values in separate files
- [ ] `ChunkedStorage` as hybrid between the two, multiple files where each file contains several entries from the table

* What exactly should we version using _atomic files_? Each value, each chunk or the whole table only?

**Comment by kirillt** [comment]
@twitu as soon as the simplest `FileStorage` abstraction is ready, we can start using it in particular implementations like `TagStorage` and `ScoreStorage` and build Tauri components on top of them.

**Comment by twitu** [comment]
Added FileStorage struct with same functionality as [Kotlin implementation](https://github.com/ARK-Builders/arklib-android/blob/main/lib/src/main/java/dev/arkbuilders/arklib/data/storage/FileStorage.kt#L35) in [889638f](https://github.com/ARK-Builders/ark-rust/commit/889638fc98888f26791e670eb64e9cbbfce10f3b)

* Read data from file into a mapping from `ResourceId` to value
* Write data mapping from `ResourceId` to value to file
* Verify file version
* Delete file when dropped

**Comment by twitu** [comment]
The next step is to implement specific implementations for `TagStorage` and `ScoreStorage`. After looking at the implementations for [tags](https://github.com/ARK-Builders/arklib-android/blob/377734870453889f3e9a8821bb1cac3f7f299ab8/lib/src/main/java/dev/arkbuilders/arklib/user/tags/Tags.kt#L6) and [score](https://github.com/ARK-Builders/arklib-android/blob/377734870453889f3e9a8821bb1cac3f7f299ab8/lib/src/main/java/dev/arkbuilders/arklib/user/score/Score.kt#L7) it's clear that they are aliases for Int and String or Sets of String. These can be written to a file by the generic `FileStorage` implementation.

However, the android implementation assumes that the keys are resource ids. The FileStorage can write any key that can be converted to a string. So for the specialized implementation where will the keys come from?

**Comment by kirillt** [comment]
We have the `FolderStorage` left to implement, `ChunkedStorage` will be done sometime in the future.
